/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jconga;

import baraja.Baraja;
import baraja.Carta;
import java.awt.Color;
import java.awt.Rectangle;
import java.util.ArrayList;
import javax.swing.border.LineBorder;


/**
 *
 * @author luiss
 */
public class Base extends javax.swing.JFrame {
    
    //Creamos un objeto para la baraja y uno para el mazo
    Baraja baraja = new Baraja();
    ArrayList<Carta> mazo = new ArrayList<>();
    
    //Creamos objetos para la mano del jugador y para su botonera
    ArrayList<Carta> mano = new ArrayList<>();
    ButtonCarta[] botonesMano = new ButtonCarta[8];
    
    //Creamos un objeto para guardar los jugadores participantes
    ArrayList<Jugador> jugadores = new ArrayList<>();
    
    //Variables auxiliares para el seguimiento de las acciones del juego
    int cartasSeleccionadas = 0;
    int cartasEnMano = 0;
    
    /**
     * Creates new form Base
     */
    public Base() {
        initComponents();
        
        PrepararVentana();
        
    }
    
    /**
     * Prepara la ventana para el juego.
     */
    private void PrepararVentana(){
        //Creamos un objeto Carta para representar la baraja
        Carta imgBaraja = new Carta(0, "reves");
        btnBaraja.setCarta(imgBaraja);
        btnBaraja.ActualizarImagen();
        
        //Creamos y asignamos botones a la botonera del usuario
        botonesMano[0] = btnCarta1;
        botonesMano[1] = btnCarta2;
        botonesMano[2] = btnCarta3;
        botonesMano[3] = btnCarta4;
        botonesMano[4] = btnCarta5;
        botonesMano[5] = btnCarta6;
        botonesMano[6] = btnCarta7;
        botonesMano[7] = btnCarta8;
        
        //PARA PRUEBAS: creamos una partida con dos jugadores        
        Jugador j1 = new Jugador();
        Jugador j2 = new Jugador();
        
        jugadores.add(j1);
        jugadores.add(j2);
        
        //El 'primer jugador' es 'mano': baraja y reparte las cartas
        //Esto debe mejorarse al pasar a un juego en red.
        jugadores.get(0).Barajar(baraja);
        jugadores.get(0).Repartir(jugadores, baraja);
        
        //Se actualiza la cantidad de cartas en la baraja, en la mano
        // y se activa la botonera.
        ActualizarCantBaraja();
        ActualizarMano();
        ActivarBotones();
    }
    
    /**
     * Permite actualizar la cantidad de cartas en la baraja.
     */
    private void ActualizarCantBaraja(){
        //Se obtienen la catidad de cartas en la baraja y en el mazo
        int cantidadB = baraja.cartas.size();
        int cantidadM = mazo.size();
        
        //Visualización de cantidades en la GUI
        lblCartasBaraja.setText(cantidadB+"");
        lblCartasMazo.setText(cantidadM+"");
        
        //Se crea una carta nula
        Carta carta = null;
        
        //Si el mazo no esta vacío, se toma la primer carta
        if(cantidadM > 0){
            carta = mazo.get(0);
            
        }
        else{
            carta = new Carta(0,"vacia");
        }
        btnMazo.setCarta(carta);
        btnMazo.ActualizarImagen();
    }
    
    private void ActualizarMano(){
        ArrayList<Carta> mano = jugadores.get(0).mano;
        Carta carta = null;
        for(int i = 0; i<8; i++){
            if ( i < mano.size() ) {
                carta = mano.get(i);
            }
            else{
                carta = new Carta(0, "vacia");
            }
            botonesMano[i].setCarta(carta);
            botonesMano[i].ActualizarImagen();
        }
        cartasEnMano = mano.size();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCarta2 = new jconga.ButtonCarta();
        btnCarta1 = new jconga.ButtonCarta();
        btnCarta3 = new jconga.ButtonCarta();
        btnCarta4 = new jconga.ButtonCarta();
        btnCarta5 = new jconga.ButtonCarta();
        btnCarta6 = new jconga.ButtonCarta();
        btnCarta7 = new jconga.ButtonCarta();
        btnCarta8 = new jconga.ButtonCarta();
        btnBaraja = new jconga.ButtonCarta();
        btnMazo = new jconga.ButtonCarta();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblCartasBaraja = new javax.swing.JLabel();
        lblCartasMazo = new javax.swing.JLabel();
        btnTirarCarta = new javax.swing.JButton();
        btnHacerJuego = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(1100, 600));
        setPreferredSize(new java.awt.Dimension(1100, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCarta2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        btnCarta2.setName(""); // NOI18N
        btnCarta2.setPreferredSize(new java.awt.Dimension(108, 164));
        btnCarta2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCarta2MouseClicked(evt);
            }
        });
        getContentPane().add(btnCarta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, -1, -1));

        btnCarta1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        btnCarta1.setName(""); // NOI18N
        btnCarta1.setPreferredSize(new java.awt.Dimension(108, 164));
        btnCarta1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCarta1MouseClicked(evt);
            }
        });
        getContentPane().add(btnCarta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));

        btnCarta3.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        btnCarta3.setName(""); // NOI18N
        btnCarta3.setPreferredSize(new java.awt.Dimension(108, 164));
        btnCarta3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCarta3MouseClicked(evt);
            }
        });
        getContentPane().add(btnCarta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, -1, -1));

        btnCarta4.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        btnCarta4.setName(""); // NOI18N
        btnCarta4.setPreferredSize(new java.awt.Dimension(108, 164));
        btnCarta4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCarta4MouseClicked(evt);
            }
        });
        getContentPane().add(btnCarta4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, -1, -1));

        btnCarta5.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        btnCarta5.setName(""); // NOI18N
        btnCarta5.setPreferredSize(new java.awt.Dimension(108, 164));
        btnCarta5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCarta5MouseClicked(evt);
            }
        });
        getContentPane().add(btnCarta5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 370, -1, -1));

        btnCarta6.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        btnCarta6.setName(""); // NOI18N
        btnCarta6.setPreferredSize(new java.awt.Dimension(108, 164));
        btnCarta6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCarta6MouseClicked(evt);
            }
        });
        getContentPane().add(btnCarta6, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 370, -1, -1));

        btnCarta7.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        btnCarta7.setName(""); // NOI18N
        btnCarta7.setPreferredSize(new java.awt.Dimension(108, 164));
        btnCarta7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCarta7MouseClicked(evt);
            }
        });
        getContentPane().add(btnCarta7, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 370, -1, -1));

        btnCarta8.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        btnCarta8.setName(""); // NOI18N
        btnCarta8.setPreferredSize(new java.awt.Dimension(108, 164));
        btnCarta8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCarta8MouseClicked(evt);
            }
        });
        getContentPane().add(btnCarta8, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 370, -1, -1));

        btnBaraja.setPreferredSize(new java.awt.Dimension(108, 164));
        btnBaraja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBarajaMouseClicked(evt);
            }
        });
        getContentPane().add(btnBaraja, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, -1, -1));

        btnMazo.setPreferredSize(new java.awt.Dimension(108, 164));
        btnMazo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMazoMouseClicked(evt);
            }
        });
        getContentPane().add(btnMazo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, -1, -1));

        jLabel1.setText("Baraja");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, -1, -1));

        jLabel2.setText("Mazo");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, -1, -1));

        lblCartasBaraja.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblCartasBaraja.setText("...");
        getContentPane().add(lblCartasBaraja, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 260, -1, -1));

        lblCartasMazo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblCartasMazo.setText("...");
        getContentPane().add(lblCartasMazo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, -1, -1));

        btnTirarCarta.setBackground(new java.awt.Color(255, 255, 255));
        btnTirarCarta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jconga/imagen/descartarCarta.png"))); // NOI18N
        btnTirarCarta.setText("Tirar Carta");
        btnTirarCarta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnTirarCarta.setEnabled(false);
        btnTirarCarta.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnTirarCarta.setMaximumSize(new java.awt.Dimension(140, 50));
        btnTirarCarta.setMinimumSize(new java.awt.Dimension(140, 50));
        btnTirarCarta.setPreferredSize(new java.awt.Dimension(140, 50));
        btnTirarCarta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTirarCartaMouseClicked(evt);
            }
        });
        getContentPane().add(btnTirarCarta, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 480, 140, 50));

        btnHacerJuego.setBackground(new java.awt.Color(255, 255, 255));
        btnHacerJuego.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jconga/imagen/juego.png"))); // NOI18N
        btnHacerJuego.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnHacerJuego.setEnabled(false);
        btnHacerJuego.setLabel("Hacer Juego");
        btnHacerJuego.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnHacerJuego.setMaximumSize(new java.awt.Dimension(140, 50));
        btnHacerJuego.setMinimumSize(new java.awt.Dimension(140, 50));
        btnHacerJuego.setPreferredSize(new java.awt.Dimension(140, 50));
        btnHacerJuego.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHacerJuegoMouseClicked(evt);
            }
        });
        getContentPane().add(btnHacerJuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 370, 140, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBarajaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBarajaMouseClicked
        // TODO add your handling code here:
        jugadores.get(0).LevantarCarta(baraja);
        DesmarcarTodas();
        ActualizarMano();
        ActualizarCantBaraja();
        ActivarBotones();
    }//GEN-LAST:event_btnBarajaMouseClicked

    private void btnCarta1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCarta1MouseClicked
        CartaSeleccionada(evt);
    }//GEN-LAST:event_btnCarta1MouseClicked

    private void btnCarta2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCarta2MouseClicked
        // TODO add your handling code here:
        CartaSeleccionada(evt);
    }//GEN-LAST:event_btnCarta2MouseClicked

    private void btnCarta3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCarta3MouseClicked
        // TODO add your handling code here:
        CartaSeleccionada(evt);
    }//GEN-LAST:event_btnCarta3MouseClicked

    private void btnCarta4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCarta4MouseClicked
        // TODO add your handling code here:
        CartaSeleccionada(evt);
    }//GEN-LAST:event_btnCarta4MouseClicked

    private void btnCarta5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCarta5MouseClicked
        // TODO add your handling code here:
        CartaSeleccionada(evt);
    }//GEN-LAST:event_btnCarta5MouseClicked

    private void btnCarta6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCarta6MouseClicked
        // TODO add your handling code here:
        CartaSeleccionada(evt);
    }//GEN-LAST:event_btnCarta6MouseClicked

    private void btnCarta7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCarta7MouseClicked
        // TODO add your handling code here:
        CartaSeleccionada(evt);
    }//GEN-LAST:event_btnCarta7MouseClicked

    private void btnTirarCartaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTirarCartaMouseClicked
        // TODO add your handling code here:
        Carta cartaSel = null;
        for (ButtonCarta btn: botonesMano) {
            if (btn.seleccionada) {
                cartaSel = btn.getCarta();
            }
        }
        jugadores.get(0).TirarCarta(cartaSel, mazo);
        DesmarcarTodas();
        ActualizarCantBaraja();
        ActualizarMano();
        ActivarBotones();
    }//GEN-LAST:event_btnTirarCartaMouseClicked

    private void btnCarta8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCarta8MouseClicked
        // TODO add your handling code here:
        CartaSeleccionada(evt);
    }//GEN-LAST:event_btnCarta8MouseClicked

    private void btnMazoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMazoMouseClicked
        // TODO add your handling code here:
        
        jugadores.get(0).LevantarCarta(mazo);
        DesmarcarTodas();
        ActualizarCantBaraja();
        ActualizarMano();
        ActivarBotones();
    }//GEN-LAST:event_btnMazoMouseClicked

    private void btnHacerJuegoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHacerJuegoMouseClicked
        // TODO add your handling code here:
        ArrayList<Carta> juego = new ArrayList<>();
        for(ButtonCarta btnCarta:botonesMano){
            
            if (btnCarta.seleccionada) {
                Carta carta = btnCarta.getCarta();
                juego.add(carta);
            }
            
        }
        
        ArmarJuego armarJuego = new ArmarJuego(this, true,juego);
        armarJuego.setVisible(true);
        //PrepararJuego prepJuego = new PrepararJuego(juego);
        //prepJuego.setVisible(true);
    }//GEN-LAST:event_btnHacerJuegoMouseClicked

    private void DesmarcarTodas(){
        cartasSeleccionadas = 0;
        for(ButtonCarta btn: botonesMano){
            btn.seleccionada = false;
            btn.Mover();
        }
    }
    
    private void CartaSeleccionada(java.awt.event.MouseEvent evt){
        ButtonCarta btn = (ButtonCarta)evt.getSource();
        System.out.println(btn.getName()+":"+btn.seleccionada);
        if (!btn.seleccionada) {
            btn.seleccionada = true;
            cartasSeleccionadas++;
        }
        else{ 
            btn.seleccionada = false;
            cartasSeleccionadas--;
        }
        
        btn.Mover();
        ActivarBotones();
        //btn.PonerBordes();
        
        
    }
    
    private void ActivarBotones(){
        if (cartasEnMano > 7 && cartasSeleccionadas == 1) {
            btnTirarCarta.setEnabled(true);
        }
        else{
            btnTirarCarta.setEnabled(false);
        }
        
        if (cartasEnMano > 7 && cartasSeleccionadas > 2) {
            btnHacerJuego.setEnabled(true);
        }
        else{
            btnHacerJuego.setEnabled(false);
        }
        
        if(cartasEnMano < 8){
            if(mazo.isEmpty()){
                btnMazo.setEnabled(false);
            }
            else{
                btnMazo.setEnabled(true);
            }
            
            if (baraja.cartas.isEmpty()) {
                btnBaraja.setEnabled(false);
            }
            else{
                btnBaraja.setEnabled(true);
            }
        }
        else{
             btnBaraja.setEnabled(false);
              btnMazo.setEnabled(false);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Base.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Base.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Base.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Base.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Base().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private jconga.ButtonCarta btnBaraja;
    private jconga.ButtonCarta btnCarta1;
    private jconga.ButtonCarta btnCarta2;
    private jconga.ButtonCarta btnCarta3;
    private jconga.ButtonCarta btnCarta4;
    private jconga.ButtonCarta btnCarta5;
    private jconga.ButtonCarta btnCarta6;
    private jconga.ButtonCarta btnCarta7;
    private jconga.ButtonCarta btnCarta8;
    private javax.swing.JButton btnHacerJuego;
    private jconga.ButtonCarta btnMazo;
    private javax.swing.JButton btnTirarCarta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblCartasBaraja;
    private javax.swing.JLabel lblCartasMazo;
    // End of variables declaration//GEN-END:variables
}
